name: Haiku

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: cpa.sh {0}
    steps:
    - uses: actions/checkout@v6
    - uses: cross-platform-actions/action@v1.2.0
      with:
        operating_system: haiku
        version: r1beta5
        memory: 2G
    - name: Install dependencies
      # newer PG ports miss pg_hmac_create and pg_tolower that somehow get pulled in :(
      # also https://github.com/haikuports/haikuports/pull/12892#issuecomment-3248334462
      run: pkgman install -y pkgconfig meson readline ncurses6_devel postgresql11_devel
    - name: Configure Meson
      run: meson setup build
    - name: Build
      run: meson compile -C build
    - name: Test
      run: build/pspg --info
