name: macOS

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v6
    - name: Install dependencies
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1
      run: |
        brew install meson
      #  libpq
      #  readline
      # ncurses
    - name: Configure Meson
      env:
        PKG_CONFIG_PATH: /opt/homebrew/opt/readline/lib/pkgconfig:/opt/homebrew/opt/libpq/lib/pkgconfig
      run: meson setup build --backend ninja
    - name: Build
      run: meson compile -C build
    - name: Test
      run: build/pspg --info
    - name: Upload Meson log
      uses: actions/upload-artifact@v7
      if: ${{ failure() }}
      with:
        name: Meson log
        path: build/meson-logs/meson-log.txt
