name: MSVC & ClangCL

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6

    - name: Cache Vcpkg
      uses: actions/cache@v5
      with:
        path: vcpkg_installed
        key: vcpkg

    - name: Install Meson
      run: |
        winget install -e --id mesonbuild.meson --silent --accept-source-agreements --accept-package-agreements
        echo "C:\Program Files\Meson" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: MSVC environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Vcpkg dependencies
      run: C:\vcpkg\vcpkg.exe install --vcpkg-root=C:\vcpkg

    - name: Configure Meson
      env:
        CC: clang-cl
      # --genvslite vs2022
      run: >-
        meson setup build --backend vs
        -Dpgroot="C:\Program Files\PostgreSQL\17" -Ddep_prefix=vcpkg_installed/x64-windows

    - name: Build
      run: meson compile -C build

    - name: Test
      env:
        PATH: "${{ github.workspace }}/vcpkg_installed/x64-windows/bin;C:/Program Files/PostgreSQL/17/bin;$env:PATH"
      run: |
        echo $env:PATH
        build\pspg.exe --info

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: Windows shlibs
        path: build/RelWithDebInfo/*
